[workspace]
resolver = "2"
members = ["engine", "packages/shutdown", "worker"]

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["The KSOX Team"]
description = "The KSOX Project"

[workspace.dependencies]
axum = { version = "0.6", features = [
    "headers",
    "http2",
    "macros",
    "multipart",
    "tracing",
    "ws",
] }
chrono = { version = "0.4.26", features = ["serde"] }
futures = "0.3"
hyper = { version = "0.14", features = ["full"] }
thiserror = "1"
tokio = { version = "1.32", features = ["full", "tracing"] }
tokio-stream = "0.1.14"
tracing = "0.1"
tracing-subscriber = "0.3"
