apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ksox

resources:
  - ./../../resources
  - ./redis.yaml
  - ./surrealdb.yaml

patches:
  - path: redis.patch.yaml
    target:
      kind: Deployment
      labelSelector: "app=redis"
  - path: surrealdb.patch.yaml
    target:
      kind: Deployment
      labelSelector: "app=surrealdb"

secretGenerator:
  - name: secrets
    env: ./envs/secrets.env

configMapGenerator:
  - name: config
    env: ./envs/config.env

generatorOptions:
  disableNameSuffixHash: true
