apiVersion: v1
kind: Service
metadata:
  name: redisinsights
spec:
  selector:
    app: redis
  ports:
    - name: redisinsights-tcp
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: redisinsights-udp
      protocol: UDP
      port: 8001
      targetPort: 8001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: redis.test
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: redis
                port:
                  number: 6379
    - host: redisinsights.test
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: redisinsights
                port:
                  number: 8001
