apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: surrealdb
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: surrealdb.test
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: surrealdb
                port:
                  number: 80
