name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  KSOX_SERVER_JWT_SECRET: 620c6abfe023e6e30645e48be1cc78c52792dfc6a2914aa1eb1f6dc567216d79
  KSOX_SERVER_API_BIND: 0.0.0.0:80

jobs:
  prettier:
    runs-on: self-hosted
    steps:
      - uses: actions/setup-node@v3
      - name: Check formatting with prettier
        run: npx prettier --check .
  fmt:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting with cargo fmt
        run: cargo fmt -- --check
  clippy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: cargo clippy -- -D warnings
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --verbose
