name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  KSOX_SERVER_WORKER_ADDRESS: 0.0.0.0:80

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check formatting
        run: cargo fmt -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Clippy
        run: cargo clippy -- -D warnings
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: cargo test --verbose
